/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haofengkeji_hdread_MainActivity_UpdateThread */

#ifndef _Included_com_haofengkeji_hdread_MainActivity_UpdateThread
#define _Included_com_haofengkeji_hdread_MainActivity_UpdateThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
