/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haofengkeji_hdread_MainActivity_E_DIFFICULTLEVEL */

#ifndef _Included_com_haofengkeji_hdread_MainActivity_E_DIFFICULTLEVEL
#define _Included_com_haofengkeji_hdread_MainActivity_E_DIFFICULTLEVEL
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
