/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haofengkeji_hdread_MainActivity_StartThread */

#ifndef _Included_com_haofengkeji_hdread_MainActivity_StartThread
#define _Included_com_haofengkeji_hdread_MainActivity_StartThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_haofengkeji_hdread_MainActivity_StartThread_MIN_PRIORITY
#define com_haofengkeji_hdread_MainActivity_StartThread_MIN_PRIORITY 1L
#undef com_haofengkeji_hdread_MainActivity_StartThread_NORM_PRIORITY
#define com_haofengkeji_hdread_MainActivity_StartThread_NORM_PRIORITY 5L
#undef com_haofengkeji_hdread_MainActivity_StartThread_MAX_PRIORITY
#define com_haofengkeji_hdread_MainActivity_StartThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
