/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haofengkeji_hdread_MainActivity_MyThread2 */

#ifndef _Included_com_haofengkeji_hdread_MainActivity_MyThread2
#define _Included_com_haofengkeji_hdread_MainActivity_MyThread2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_haofengkeji_hdread_MainActivity_MyThread2_MIN_PRIORITY
#define com_haofengkeji_hdread_MainActivity_MyThread2_MIN_PRIORITY 1L
#undef com_haofengkeji_hdread_MainActivity_MyThread2_NORM_PRIORITY
#define com_haofengkeji_hdread_MainActivity_MyThread2_NORM_PRIORITY 5L
#undef com_haofengkeji_hdread_MainActivity_MyThread2_MAX_PRIORITY
#define com_haofengkeji_hdread_MainActivity_MyThread2_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
